# frozen_string_literal: true
# A sample Gemfile
source "https://rubygems.org"
gem "sinatra"
gem "thin"
gem "faker"
gem 'rack', '<2.0'
gem 'activerecord', '4.2.5'
gem 'sinatra-activerecord'
gem 'rake'
gem 'require_all'
gem 'sqlite3'
gem 'tux'
gem 'pg'
# gem "rails"
