# frozen_string_literal: true
# A sample Gemfile
source "https://rubygems.org"
gem "sinatra"
gem "thin"
gem "faker"
gem "activerecord"
gem "sinatra-activerecord"
gem "rake"
gem 'sinatra-flash'

group :production do
    gem 'pg', '0.12.2'
end
group :development do
    gem 'pg', '0.12.2'
end
# gem "rails"
